import type { StudentData } from "./types"

export const sampleData: StudentData[] = [
  {
    student_id: "1001",
    name: "Ana Silva",
    gender: "Feminino",
    age: 15,
    grade_level: "9º Ano",
    math_score: 85,
    reading_score: 92,
    writing_score: 88,
    attendance_rate: 98,
    parent_education: "Superior",
    study_hours: 12,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Sim",
    final_result: "Aprovado",
  },
  {
    student_id: "1002",
    name: "João Santos",
    gender: "Masculino",
    age: 16,
    grade_level: "9º Ano",
    math_score: 78,
    reading_score: 65,
    writing_score: 70,
    attendance_rate: 85,
    parent_education: "Médio",
    study_hours: 8,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Não",
    final_result: "Aprovado",
  },
  {
    student_id: "1003",
    name: "Mariana Oliveira",
    gender: "Feminino",
    age: 15,
    grade_level: "9º Ano",
    math_score: 92,
    reading_score: 95,
    writing_score: 90,
    attendance_rate: 100,
    parent_education: "Superior",
    study_hours: 15,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Sim",
    final_result: "Aprovado",
  },
  {
    student_id: "1004",
    name: "Pedro Costa",
    gender: "Masculino",
    age: 16,
    grade_level: "9º Ano",
    math_score: 65,
    reading_score: 70,
    writing_score: 68,
    attendance_rate: 75,
    parent_education: "Fundamental",
    study_hours: 5,
    internet_access: "Não",
    lunch_type: "Reduzida",
    extra_activities: "Não",
    final_result: "Reprovado",
  },
  {
    student_id: "1005",
    name: "Juliana Lima",
    gender: "Feminino",
    age: 15,
    grade_level: "9º Ano",
    math_score: 75,
    reading_score: 82,
    writing_score: 80,
    attendance_rate: 90,
    parent_education: "Médio",
    study_hours: 10,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Sim",
    final_result: "Aprovado",
  },
  {
    student_id: "1006",
    name: "Lucas Ferreira",
    gender: "Masculino",
    age: 14,
    grade_level: "8º Ano",
    math_score: 88,
    reading_score: 75,
    writing_score: 72,
    attendance_rate: 95,
    parent_education: "Superior",
    study_hours: 11,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Sim",
    final_result: "Aprovado",
  },
  {
    student_id: "1007",
    name: "Beatriz Almeida",
    gender: "Feminino",
    age: 14,
    grade_level: "8º Ano",
    math_score: 70,
    reading_score: 85,
    writing_score: 88,
    attendance_rate: 92,
    parent_education: "Médio",
    study_hours: 9,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Sim",
    final_result: "Aprovado",
  },
  {
    student_id: "1008",
    name: "Gabriel Souza",
    gender: "Masculino",
    age: 15,
    grade_level: "8º Ano",
    math_score: 60,
    reading_score: 62,
    writing_score: 58,
    attendance_rate: 70,
    parent_education: "Fundamental",
    study_hours: 4,
    internet_access: "Não",
    lunch_type: "Reduzida",
    extra_activities: "Não",
    final_result: "Reprovado",
  },
  {
    student_id: "1009",
    name: "Carolina Martins",
    gender: "Feminino",
    age: 14,
    grade_level: "8º Ano",
    math_score: 82,
    reading_score: 88,
    writing_score: 85,
    attendance_rate: 96,
    parent_education: "Superior",
    study_hours: 12,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Sim",
    final_result: "Aprovado",
  },
  {
    student_id: "1010",
    name: "Rafael Pereira",
    gender: "Masculino",
    age: 15,
    grade_level: "8º Ano",
    math_score: 75,
    reading_score: 70,
    writing_score: 72,
    attendance_rate: 85,
    parent_education: "Médio",
    study_hours: 7,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Não",
    final_result: "Aprovado",
  },
  {
    student_id: "1011",
    name: "Isabela Gomes",
    gender: "Feminino",
    age: 13,
    grade_level: "7º Ano",
    math_score: 90,
    reading_score: 92,
    writing_score: 95,
    attendance_rate: 98,
    parent_education: "Superior",
    study_hours: 14,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Sim",
    final_result: "Aprovado",
  },
  {
    student_id: "1012",
    name: "Matheus Ribeiro",
    gender: "Masculino",
    age: 13,
    grade_level: "7º Ano",
    math_score: 78,
    reading_score: 75,
    writing_score: 72,
    attendance_rate: 88,
    parent_education: "Médio",
    study_hours: 8,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Sim",
    final_result: "Aprovado",
  },
  {
    student_id: "1013",
    name: "Laura Cardoso",
    gender: "Feminino",
    age: 13,
    grade_level: "7º Ano",
    math_score: 85,
    reading_score: 90,
    writing_score: 88,
    attendance_rate: 94,
    parent_education: "Superior",
    study_hours: 11,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Sim",
    final_result: "Aprovado",
  },
  {
    student_id: "1014",
    name: "Diego Rocha",
    gender: "Masculino",
    age: 14,
    grade_level: "7º Ano",
    math_score: 55,
    reading_score: 58,
    writing_score: 52,
    attendance_rate: 65,
    parent_education: "Fundamental",
    study_hours: 3,
    internet_access: "Não",
    lunch_type: "Reduzida",
    extra_activities: "Não",
    final_result: "Reprovado",
  },
  {
    student_id: "1015",
    name: "Camila Barbosa",
    gender: "Feminino",
    age: 13,
    grade_level: "7º Ano",
    math_score: 80,
    reading_score: 85,
    writing_score: 82,
    attendance_rate: 91,
    parent_education: "Médio",
    study_hours: 9,
    internet_access: "Sim",
    lunch_type: "Padrão",
    extra_activities: "Sim",
    final_result: "Aprovado",
  },
]
